[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
lib_deps =
    fastled/FastLED@^3.9.0
    h2zero/NimBLE-Arduino@^2.2.3
    kosme/arduinoFFT@^2.0.4
build_flags =
    -DFASTLED_ESP32_S3
    -DCONFIG_BT_NIMBLE_ROLE_BROADCASTER
    -DCONFIG_BT_NIMBLE_ROLE_PERIPHERAL
